# Generated by Django 5.2.7 on 2026-06-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255, verbose_name='Nome do Arquivo')),
                ('validade', models.DateField(verbose_name='Validade')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['cliente', 'validade'],
            },
        ),
        migrations.CreateModel(
            name='ControleNSU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('NFE', 'NF-e'), ('CTE', 'CT-e'), ('NFSE', 'NFS-e'), ('NFCE', 'NFC-e')], max_length=5, verbose_name='Tipo de Documento')),
                ('ultimo_nsu', models.BigIntegerField(default=0, verbose_name='Último NSU')),
                ('max_nsu', models.BigIntegerField(default=0, verbose_name='Max NSU')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Controle NSU',
                'verbose_name_plural': 'Controles NSU',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(db_index=True, max_length=44, unique=True, verbose_name='Chave de Acesso')),
                ('tipo_documento', models.CharField(choices=[('NFE', 'NF-e'), ('CTE', 'CT-e'), ('NFSE', 'NFS-e'), ('NFCE', 'NFC-e')], max_length=5, verbose_name='Tipo')),
                ('emitente', models.CharField(max_length=255, verbose_name='Emitente')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor (R$)')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('competencia', models.CharField(db_index=True, max_length=7, verbose_name='Competência')),
                ('status', models.CharField(choices=[('CAPTURADO', 'Capturado'), ('MANIFESTADO', 'Manifestado'), ('COMPLETO', 'Completo')], default='CAPTURADO', max_length=15, verbose_name='Status')),
                ('metadados', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='LogCaptura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=5, verbose_name='Tipo')),
                ('executado_em', models.DateTimeField(auto_now_add=True)),
                ('sucesso', models.BooleanField(verbose_name='Sucesso')),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem')),
            ],
            options={
                'verbose_name': 'Log de Captura',
                'verbose_name_plural': 'Logs de Captura',
                'ordering': ['-executado_em'],
            },
        ),
        migrations.CreateModel(
            name='Xml',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(verbose_name='Conteúdo XML')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'XML',
                'verbose_name_plural': 'XMLs',
            },
        ),
    ]
