# Generated by Django 5.2.7 on 2026-06-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0003_create_cliente_refactor_fks'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='conteudo_criptografado',
            field=models.BinaryField(blank=True, null=True, verbose_name='Conteúdo do certificado (.pfx) criptografado em AES'),
        ),
    ]
