# Generated by Django 5.2.7 on 2026-06-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0004_certificado_conteudo_criptografado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlensu',
            options={'ordering': ['id'], 'verbose_name': 'Controle NSU', 'verbose_name_plural': 'Controles NSU'},
        ),
        migrations.AddField(
            model_name='certificado',
            name='senha_criptografada',
            field=models.BinaryField(blank=True, null=True, verbose_name='Senha do certificado criptografada em AES'),
        ),
    ]
