# Generated by Django 5.2.7 on 2026-06-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0009_documento_papel_nfse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='chave',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Chave de Acesso'),
        ),
    ]
