# Generated by Django 5.2.7 on 2026-06-19 08:17

import os
from django.db import migrations


def criar_usuario_botoderma(apps, schema_editor):
    raw = os.environ.get('CLIENT_USER_1', '')
    parts = raw.split(':')
    if len(parts) < 2:
        return  # env var ausente — pula

    username = parts[0]
    password = parts[1]

    from django.contrib.auth import get_user_model
    User = get_user_model()
    user, _ = User.objects.get_or_create(username=username)
    user.is_active = True
    user.set_password(password)
    user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0010_chave_max_length_50'),
    ]

    operations = [
        migrations.RunPython(criar_usuario_botoderma, migrations.RunPython.noop),
    ]
