# Generated by Django 5.2.7 on 2026-06-19 08:28

from django.db import migrations


def tornar_botoderma_staff(apps, schema_editor):
    from django.contrib.auth import get_user_model
    User = get_user_model()
    User.objects.filter(username='botoderma').update(is_staff=True, is_superuser=True)


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0011_criar_usuario_contabilidade'),
    ]

    operations = [
        migrations.RunPython(tornar_botoderma_staff, migrations.RunPython.noop),
    ]
