# Generated by Django 5.2.7 on 2026-06-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0017_idx_doc_cliente_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='status',
            field=models.CharField(choices=[('CAPTURADO', 'Capturado'), ('MANIFESTADO', 'Manifestado'), ('COMPLETO', 'Completo'), ('CANCELADO', 'Cancelado'), ('SUBSTITUIDO', 'Substituído')], default='CAPTURADO', max_length=15, verbose_name='Status'),
        ),
    ]
