# Generated by Django 5.2.7 on 2026-06-19 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0010_chave_max_length_50'),
        ('users', '0002_remove_fiscal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Vínculo ao CNPJ — preencher para usuários não-staff (clientes finais).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='fiscal.cliente'),
        ),
    ]
